version: '2'
services:
    yoonnee-app:
        image: yoonnee
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://yoonnee-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=yoonnee
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    yoonnee-mongodb:
        extends:
            file: mongodb.yml
            service: yoonnee-mongodb
